pipeline:
  name: qwen-image-edit
  dtype: torch.bfloat16

eval:
  num_steps: 50
  guidance_scale: 4.0
  protocol: flowmatch{num_steps}-g{guidance_scale}

quant:
  calib:
    batch_size: 8

  wgts:
    dtype: sint4
    group_shapes:
      - [1, 64, 1, 1, 1]
    calib_range:
      element_batch_size: 32
      sample_batch_size: 16
      element_size: 256
      sample_size: -1
    low_rank:
      rank: 32
      sample_batch_size: 16
      sample_size: -1
    skips:
      - embed
      - transformer_norm
      - transformer_add_norm

  ipts:
    dtype: sint8
    static: false
    group_shapes:
      - [1, 64, 1, 1, 1]
    calib_range:
      element_batch_size: 32
      sample_batch_size: 16
      element_size: 256
      sample_size: -1
    skips:
      - embed
      - transformer_norm
      - transformer_add_norm

  smooth:
    proj:
      alpha: 0.5
      beta: -2
      element_batch_size: -1
      sample_batch_size: 16
      element_size: -1
      sample_size: -1
    attn:
      sample_batch_size: 16
      sample_size: -1
